apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-aes3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-aes3
    app.kubernetes.io/part-of: boot
  name: java-springboot-hello-aes3
  namespace: bsutter-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: java-springboot-hello-aes3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: java-springboot-hello-aes3
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:d2f673d7e90653831267255e67c034f0d7cdfbcc152c8ba38cdb6e4220dc1ecd
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
